spring:
  data:
    mongodb:
      database: cms
      host: localhost
      port: 27017
  datasource:
    # url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:mysql://localhost:3306/postgresdb
    username: root
    password: erick
    driver-class-name: com.mysql.cj.jdbc.Driver
    # username: postgres
    # password: cms@springfive
    # driver-class-name: org.postgresql.Driver

jpa:
  show-sql: true
  generate-ddl: true
  